# Generated by Django 2.1.4 on 2019-02-23 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190223_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks_as_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
