# Generated by Django 2.1.4 on 2019-01-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.URLField(default='https://picsum.photos/1000/?random'),
            preserve_default=False,
        ),
    ]
